### ISSUE TITLE
tenpy.models.lattice.get_order_grouped(shape, groups) in x-direction first

### ISSUE THREAD

**Issue by henrik-dreyer** [tenpy/tenpy#122]
I'm using iDMRG on a cylinder with a Lx=2 unit cell. There are interactions between the unit cells. It would therefore be good to have the ordering go in x first and then snake up and go around the cylinder. As far as I can tell, tenpy.models.lattice.get_order_grouped(shape, groups) must go in y-direction first (which is by definition the direction that is not infinite), is that correct?

**Comment by jhauschild** [comment]
Indeed, `get_order_grouped` goes y first, then x. 
I've now allowed to specify another entry in the tuple `order=('grouped', groups, priority)` for the Lattice and corresponding argument in `get_order_grouped` such that e.g. `order=('grouped', groups, [1, 0, 2])` should probably do what you want.
Let me know if this is not general enough!

What system are you looking at, that this is a better ordering? Do you really expect alternating strong-weak coupling in x-direction? Otherwise going in x-direction first won't really help, will it?
