### ISSUE TITLE
BUG: conditional statement for flat_index doesn't handle NoneType

### ISSUE THREAD

**Issue by pms52** [tenpy/tenpy#136]
**Describe the bug**

When attempting to calculate the expectation value of an MPO, it looks like an unhandled exception can occur if the MPO.get_IdL function (in mpo.py) returns None. The comments in this function indicate that this is possible.

This leads to an exception being raised on line 880 of /tenpy/linalg/charges.py, in get_qindex, when checking:

```if flat_index < 0:```

Apparently this is valid in Python 2.x, but in Python 3.x this causes a TypeError if flat_index is None.

**Error traceback**
```File "/home/pms52/TeNPy/tenpy/networks/mpo.py", line 623, in expectation_value
  File "/TeNPy/tenpy/networks/mpo.py", line 623, in expectation_value
    return MPOEnvironment(psi, self, psi).full_contraction(0)
  File "/TeNPy/tenpy/networks/mpo.py", line 1747, in __init__
    init_LP = self.init_LP(0)
  File "/TeNPy/tenpy/networks/mpo.py", line 1782, in init_LP
    init_LP = init_LP.add_leg(leg_mpo, IdL, axis=1, label='wR')
  File "/TeNPy/tenpy/linalg/np_conserved.py", line 1133, in add_leg
    qi, _ = leg.get_qindex(i)
  File "/TeNPy/tenpy/linalg/charges.py", line 880, in get_qindex
    if flat_index < 0:
TypeError: '<' not supported between instances of 'NoneType' and 'int'
```

**Comment by Jakob-Unfried** [comment]
In order to form `LP`, we need to know `IdL`.
So failure if `IdL is None` is expected.
By now there are a bunch of checks for `IdL is not None` such as [this one](https://github.com/tenpy/tenpy/blob/8001dd5d8565390653c7b0e7d7a21894049bc4c3/tenpy/networks/mpo.py#L2103).

Additionally, your particular case is covered by [documentation](https://github.com/tenpy/tenpy/blob/8001dd5d8565390653c7b0e7d7a21894049bc4c3/tenpy/networks/mpo.py#L1969) of  `MPOEnvironment.__init__`; the `MPO` from which you create the environment must have `IdL` and `IdR` set on the relevant bonds.

Maybe we should explicitly check if the relevant `IdL` and `IdR` are set in `MPOEnvironment.__init__` and raise an infromative error, if they are not.

I would not change anything else.
@jhauschild ?

**Comment by Jakob-Unfried** [comment]
Have improved the error message so it is clear that failure if `IdL is None` is intended and that the MPO needs to set it.

`MPO`s which come from tenpy, e.g. from a model, should have the respective `IdL`. If you still encounter this problem from such an MPO, please open a new issue.

Custom `MPO`s need to set `IdL` and `IdR` on the respective bonds in order to work with `MPOEnvironment`
