### ISSUE TITLE
tdvp: (1, 0, [1,0]) nn-bond does not evolve state (honeycomb lattice)

### ISSUE THREAD

**Issue by mgbukov** [tenpy/tenpy#144]
**Describe the bug**
algorithms: tdvp (real time evolution)

I'm not sure if this is a bug, or just me being new to TeNPy: I constructed an `SxSx` (1, 0, [1,0]) nn-bond MPOModel on a (2,2)-honeycomb lattice, and I am trying to evolve with it a z-polarized initial state using `tdvp`. I measure the `Sz` magnetization which is expected to change after the first `tdvp`-step, but it doesn't. 

- switching the interaction type to `SySy`, and keeping the bond the same, doesn't cause the z-magnetization to change either
- switching to a different bond, both the `SySy` and the `SxSx` interactions give a change in the z-mag, as expected. 

Most likely I'm doing something wrong, but I can't yet locate what. Any ideas are much appreciated!

**Minimal example or code extract**
Here's an example code to run:
[bug.txt](https://github.com/tenpy/tenpy/files/7321470/bug.txt)

output: `Z = 4.00000`
expected output: `Z = 3.99750`

**Error traceback**
N/A

**Comment by jhauschild** [comment]
Hi Marin, welcome to TeNPy :)

This issue is not a bug of TeNPy, it's a limitation of TDVP trying to keep the MPS bond dimension fixed and starting from a product state.
While SingleSite TDVP strictly keeps the MPS bond dimension fixed, two-site TDVP can increase it *only* if you get a non-trivial evolution (increasing the bond dimension on the given bond you evolve). This is not the case here, because you don't have nearest-neighbor interactions:
```
> print(H.all_coupling_terms().to_TermList())
1.00000 * Sx_2 Sx_4 +
1.00000 * Sx_3 Sx_5
```
e.g. when trying to evolve sites 2-3, the "Sx_4" and "Sx_5" are projected out, so the total effective H on sites 2-3 is zero.

The solution is probably to use another time evolution algorithm to initially increase the MPS bond dimension; after that TDVP should work as expected as well. Indeed, after one time step with the ExpMPOEvolution, I find that TDVP also changes total Sz.
