### ISSUE TITLE
What is the role of tenpy.networks.mps.MPS.norm ?

### ISSUE THREAD

**Issue by aaeberharter** [tenpy/tenpy#165]
Not really a bug, I was just wondering what the use is of keeping the `norm` member variable. For example in this code
```
psi.canonical_form(renormalize=True)
print(psi.overlap(psi))
```
One would assume that psi is normalized and <psi|psi> gives one, instead tenpy returns `psi.norm**2` which seems to be a more or less random variable.

What is the purpose of `renormalize = True` to the function `canonical_form` ?

**Comment by jhauschild** [comment]
This is not really a bug, so I didn't reply immediately. Sorry that it took me so long to get back to this, I hope this clarifies things.

If you write an MPS, you can scale any of the tensors to change the norm of the overall MPS. However, that's a bad idea if you want to stay in canonical form, since the orthogonality conditions for left-canonical A and right-canonical B would no longer hold. Rather, we keep the tensors all normalized in canonical form, and always have norm(S)=1 for the schmidt values S as well, and rather have a separate flag `psi.norm` to keep track of the overall, global norm.

In standard DMRG, you consider the MPS as a variational wavefunction. In that case, the overall norm doesn't matter, if you define expectation values as `<X> = <psi|X|psi>/<psi|psi>`, similar as the phase doesn't matter.
However, as soon as you have multiple MPS, e.g. when doing time evolution or if you apply local operators, the norm (and relative phase) matter.
Consider the following snippet:
```python
psi = MPS(...)
phi = psi.copy()
phi.apply_local_op(10, 'X')
print(phi.overlap(psi))
```
Here you expect to get the same as `psi.expectation_value('X')[10]`, right?
To make that happen, we have to keep track of the change of the norm induced by applying the (possibly non-unitary) operator to `phi`.
Similarly, when you apply MPOs, e.g. approximations of exp(-beta H), you might want to keep track of the norm.

As made clear above, psi.canonical_form() needs to normalize all the tensors when bringing them into canonical form.
When the tensor are not in canonical from (for whatever reason, e.g. because you manually applied local operators, or due to too much truncation), we can decide to keep track (renormalize=False) or discard that norm. 
As stated in the documentation, `psi.canonical_form(renormalize=True)` only says that you don't want to *update* psi.norm (when the tensors are not properly normalized for whatever reason), but it does not reset it to 1.

If you want a guaranteed norm-1 state, just use an explicit
```
psi.canonical_form()
psi.norm = 1
```
