### ISSUE TITLE
npc.tensordot drops labels when using axes=0

### ISSUE THREAD

**Issue by starsfordummies** [tenpy/tenpy#189]
While playing around I ran into some unexpected (for me at least) behavior for npc.tensordot() when called with the axes=0 option - from what I understand it should be the same as npc.outer(), but somehow when doing it eg. with two simple vectors, the axes labels of the first get lost along the way, so for example:

```
import tenpy.linalg.np_conserved as npc

v1 = npc.Array.from_ndarray_trivial([1,2,3],labels=['one'])
v2 = npc.Array.from_ndarray_trivial([2,3,4],labels=['two'])

tdot = npc.tensordot(v1,v2,axes=0)

tdot
```

will give 
```
<npc.Array shape=(3, 3) labels=['two']>
```

I had a quick look and a possible fix might be as simple as pulling the `elif axes=0` check up in the tensordot function, so that outer() gets called before other possible messups occur inbetween, something along the lines of https://github.com/tenpy/tenpy/commit/af86845bb3cea9f06ba050a5f9cdb5437874c068

For some simple cases it seems to be working fine, I didn't check whether this breaks anything else though.

**Comment by jhauschild** [comment]
Thanks for pointing it out!
The case above the `axes=0` is an optimization, but it indeed didn't handle the labels correctly.
The issue was in the end of the `tensordot` function, that `labels[:-axes]` returned an empty list rather than the whole one...
Tricky indexing error with pythons negative-index convention.
I've already pushed the (one-line) fix, will merge it as soon as the tests pass
