### ISSUE TITLE
Error specifying charge sector in correlation_length

### ISSUE THREAD

**Issue by aaronszasz** [tenpy/tenpy#289]
**Describe the bug**
In tenpy.networks.mps.MPS, correlation_length method, line 3720

If the charge sector is of the form (q1, q2), gives an error 
`ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()`

This comes from the `charge_sector != 0` comparison.  The error occurs only when the charges are given as a numpy array and not when given as a list or tuple.

Python version is 3.11.3, numpy is 1.24.3

**Minimal example or code extract**
```
T = TransferMatrix(psi,psi,charge_sector=None)
charges = T.pipe.legs[0].charges
correlation_lengths = {}
for charge in charges:
    correlation_lengths[tuple(charge)] = psi.correlation_length(charge_sector=charge)/(2*L)
```

[Also, is there a better way to get a list of all nonzero sectors of the transfer matrix?]

**Comment by jhauschild** [comment]
Again, a somewhat easy fix, but then I noticed that I should improve some more things....

You shouldn't take `T.pipe.legs[0].charges`, but just `T.pipe.legs.charges` - you could see the difference if the MPS has legs with charges `[[-1], [1]]`, then the pipe will have charges `[[-2], [0], [2]]`, and only those are valid. You can drop the `[-2]`, though if you realize that the correlation length of the negative charge is the same due to the symmetry between bra/ket in the transfer matrix, as I've argued in the docstring of the new convenience function `MPS.correlation_length_charge_sectors()`.

Also, I realized that such an outer loop is quite inefficient, as it recalculates the eigenvector in the 0 charge sector over and over again to get the eigenvalue 1 to compare to.
As a work-around, you can now
1) disable this behaviour by putting `tol_ev0=None`, or 
2) pass a list of `charge_sector` to loop over.
