### ISSUE TITLE
Package installation bug related to numpy

### ISSUE THREAD

**Issue by martintoft1** [tenpy/tenpy#332]
**Describe the bug**
I'm trying to install the Tenpy-package through a requirements.txt-file in my repository using the command 
`pip install -r requirements.txt`, where the contents of requirements.txt-file look like the following: 
```
# Requirements for Tenpy
numpy>=1.13
scipy>=0.18
Cython>=0.29
setuptools>=30.3.0
# Tenpy itself
physics-tenpy
```

**Error traceback**
The installation results in the following error, which suggests that numpy isn't properly installed. I've tried installing numpy with a separate `pip install numpy` prior to installing the requirements-file, but I'm still left with the same error:

```
Collecting physics-tenpy (from -r requirements.txt (line 7))
  Using cached physics-tenpy-0.10.0.tar.gz (822 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "/Users/martintoft/Documents/Master/Koding/TensorQAOA/venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()

...        

        File "/private/var/folders/68/nvgkkysd0fl4ygrdkyxf3tl40000gn/T/pip-build-env-waere_fe/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 4, in <module>
      ModuleNotFoundError: No module named 'numpy'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
[Traceback]
```

Note that I'm using Python 3.12.1 and pip 23.2.1 on a Macbook Pro M1 2020.

**Comment by Jakob-Unfried** [comment]
Hi Martin,

The current release on PyPI, where pip is pulling tenpy from, is v0.10 and is quite old by now.

In particular, we merged #237 since then.
The next release, which will include #237, might just fix this issue directly.
In any case, the behavior and the possible fixes will be different.
We will not attempt to fix this issue for 0.10, and only for the next release.

Note that there are subtleties when installing these packages on apple machines with silicon (M1 / M2) chips.
See e.g. the discussion in #150.
See also [this article](https://towardsdatascience.com/how-to-manage-conda-environments-on-an-apple-silicon-m1-mac-1e29cb3bad12) discussing ways of getting an installation to run in non-native x86 architecture, at the loss of a bit of performance

**Comment by Jakob-Unfried** [comment]
Ok, so I consider this particular issue dealt with.
Feel free to reopen or open a new issue if there are still problems =)

**Comment by Jakob-Unfried** [comment]
@martintoft1 FYI, there is now a new release on PyPI.
Also AFAIK, you do not need to put tenpys dependencies in your requirements.txt.
They should get parsed recursively.
