### ISSUE TITLE
Improving estimation of RAM usage

### ISSUE THREAD

**Issue by p-thoma** [tenpy/tenpy#445]
The `estimate_RAM` method of an Algorithm and consequently also of Simulations seems to be off for the `TimeEvolutionAlgorithm` (I had no problems for other Algorithms e.g., DMRG).  For smaller bond dimensions the estimated ram (without the offset) can be off by factors of 5~10, for larger bond dimensions it can still be off by several factors.
I've identified two cases

- for e.g., a `TEBDEngine`  the `estimate_RAM`  method is not including any RAM usage from the engine (as the if clause in this method is not triggered) and only the estimated RAM for psi is returned
- for `ExpMPOEvolution` and `TDVPEngine` the if clause is triggered, but the estimate is still not accurate

**Comment by jhauschild** [comment]
Just to be clear - we overestimate the RAM, correct? Which orders of RAM in MB/GB are we talking about here?

With the estimate_RAM, we just want to provide a rough estimate of the required RAM based on the scaling of Tensor to be held in memory. 
The use case are HPC cluster environments like slurm, where you need to say how much memory you need *before* running the simulation  - but you only need a rough estimate on the order of GB, i.e. whether you need 40 or 100GB, but not whether you need 50MB or 200MB - in the latter case you would just request 1GB anyways, to be on the safe side.

For anything < 500MB, we can't even provide good estimates: just starting python and importing numpy and tenpy
can already require on the order of 100MB, but how much depends on what system you have, how you installed it etc.

That's why we don't handle the TEBD separately - we don't have significantly larger/more tensors, than we anyways have in the MPS (which is accounted for).

I guess you tried this on your spectral function calculations - there, you often have a light-cone behavior with larger chi in the middle, but usually should not reach the chi_max at the boundaries - that's why we overestimate the RAM in this case. However, we don't have a good estimate beforehand for how far out you'll reach chi_max - so we take the worst case for the estimate.

I'll close this for now - you can reopen if the estimates are actually off by several GB.
