### ISSUE TITLE
Fit for powerlaw/long-range approximated by exponentials

### ISSUE THREAD

**Issue by jhauschild** [tenpy/tenpy#78]
MPOs can naturally encode exponentially decaying interactions with very low bond dimensions.
A common method to simulate power-law long-range interactions is hence to fit them with with a bunch of exponentials and include those into the MPO. It would be nice to have such a function in TeNPy. One way to do this is outlined in the appendix of https://arxiv.org/abs/0804.3976

Also, while we're at it, we could also implement a way to add those exponentials directly to an existing Model.
This would probably require the implementation of a `ExponentialTerms` class in `tenpy.models.terms`. Instances can then be added as attributes to the CouplingModel.

**Comment by halbleben** [comment]
This may also be interesting for doing the same in higher spatial dimensions: https://arxiv.org/abs/1907.06018

**Comment by orodrigoaraizabravo** [comment]
Hello, 

I am actually implementing this exponential expansion for my own work on Tenpy. However, I ran into some issues when considering the the tow model 
<img src="https://render.githubusercontent.com/render/math?math=H=\sum_{i,r}J\lambda^rS^z_iS^z_{I+r}">. The Bulk MPO of this Hamiltonian takes the form 
<img src="https://render.githubusercontent.com/render/math?math=W_{bulk}=[[ 0, J\lambda S^z, 0],[ 0, \lambda I, S^z],[0, 0, I]]">.
However, I am running into trouble when running this because each zero in the matrix above is represented by a `None` in my code. Here is my code and the error:

CODE: 
`from tenpy.networks.site import SpinHalfSite
from tenpy.networks.mpo import MPO

spin = SpinHalfSite(conserve=None)

N = 4  # number of sites
sites = [spin] * N  # repeat entry of list N times
Id, Sz = spin.Id, spin.Sz

J = 1.
l = 0.5

W_bulk = [[  Id,  J * l * Sz, None],
          [None,        l*Id,   Sz],
          [None,        None,   Id]]

W_first = [W_bulk[0]]  # first row
W_last = [[row[-1]] for row in W_bulk]  # last column
Ws = [W_first] + [W_bulk] * (N - 2) + [W_last]
H = MPO.from_grids([spin] * N, Ws, bc='finite', IdL=0, IdR=-1)`

ERROR: 

`Traceback (most recent call last):

  File "<ipython-input-151-54e780d20afd>", line 8, in <module>
    H = MPO.from_grids([spin] * N, Ws, bc='finite', IdL=0, IdR=-1)

  File "/Users/huitadmin/psi4conda/lib/python3.6/site-packages/tenpy/networks/mpo.py", line 283, in from_grids
    legs = _calc_grid_legs_finite(chinfo, grids, Ws_qtotal, None)

  File "/Users/huitadmin/psi4conda/lib/python3.6/site-packages/tenpy/networks/mpo.py", line 1970, in _calc_grid_legs_finite
    bunch=False)

  File "/Users/huitadmin/psi4conda/lib/python3.6/site-packages/tenpy/linalg/np_conserved.py", line 3104, in detect_grid_outer_legcharge
    raise ValueError("can't derive flat charge for all indices:" + str(qflat))

ValueError: can't derive flat charge for all indices:[array([], dtype=int64), array([], dtype=int64), None]`

I noted that if I replace the "None" on the top-right corner of the MPO by a zero operator then the code runs with no issues. Is there a way to avoid putting zero operators? For a Hamiltonian with more exponentials, there will potentially be more "None" entries on the upper triangular, which worries me since I don't want to loose speed. Could you please advice?

**Comment by jhauschild** [comment]
The `None` in the top right corner is the on-site term, and there is only a single on-site term, no matter how many exponentials you add. Nevertheless, if you are really worried, you can explicitly drop the zeros with:
```python
for i in range(H.L):
    H.get_W(i, copy=False).ipurge_zeros()
```

The error is caused by the fact that the IdR index 2 on bond (0, 1) is not connected to the IdL index on bond (-1, 0), where we start to determine charges, it's a limitation in calculating the leg charges of the MPO.
Similarly on the right, i.e. also project out the last index on the bond (0, 1) and the first index on the bond (L-2, L-1):
```
W_first = [W_bulk[0][:-1]]  # first row except last column
W_second = W_bulk[:-1]  # everything except last row
W_second_to_last = [row[1:] for row in W_bulk] # everything but first column
W_last = [row[-1:] for row in W_bulk[1:]]  # last column except first row
Ws = [W_first, W_second] + [W_bulk] * (N - 4) + [W_second_to_last, W_last]
```
This should also work if you have multiple exponentials.

Finally, I'm basically done implementing the proper fix, namely including this into the TeNPy models.
I'm debugging the last parts, hopefully I can push it tomorrow....

**Comment by jhauschild** [comment]
Okay, done! 
https://tenpy.readthedocs.io/en/latest/reference/tenpy.models.model.CouplingModel.html#tenpy.models.model.CouplingModel.add_exponentially_decaying_coupling
should work now. Let me know if you have trouble using it.
